### ISSUE TITLE
Log Factotum API Calls

### ISSUE THREAD

**Issue by dmlyons2** [HumanExposure/factotum_ws#36]
As a product owner
I would like to log each request to the web services
So that I can show value for the web services

Definition of Done
1. Create a new table in our logging database for API calls
2. at a minimum log: date, time, what the URL was requested
3. Does not have to be in DB, could be file or Elastic

**Comment by mcovalt** [comment]
A brief overview of the three possible methods:

**File**: The `factotum_ws` Docker image is currently configured to output error and access logs to `stdout` and `stderr` in JSON format. Docker already captures and stores a JSON of the `stdout` and `stderr` of each container by default.

**Elasticsearch**: A new Logstash pipeline can be made to ingest log entries. One possibility is to configure Python to handle logs with the [HTTPHandler](https://docs.python.org/3/library/logging.handlers.html#httphandler) and `POST` its JSON logs to Logstashes via the [Http input plugin](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http.html). There are tons of alternative different ways to this (e.g. [gelf](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-gelf.html)/[pygelf](https://github.com/keeprocking/pygelf), [Tcp](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-tcp.html)/[SocketHandler](https://docs.python.org/3/library/logging.handlers.html#sockethandler), UNIX socket, etc.). Wiring up the connection between Logstash and `factotum_ws` should be very straightforward. Plus, the workflow for this would be directly transferable to `factotum`.

Another possibility is to set up the Docker logger to send it's captured logs to the Logstash container rather than a file. This would be even easier to implement, but I'm not sure how straightforward it would be to send the logs of one container to another. It seems like it's more focused on sending logs via the host's network.

**MySQL**: `factotum_ws` is currently setup to treat the MySQL server as read-only. Its privileges would have to be heightened and careful consideration should be made regarding how to organize migrations across the two apps and the effects of two separate Django instances writing to the same database. These questions are inevitable if the API service ever begins to accept `POST`s, but as is, the current privileges granted to `factotum_ws` are well suited to its `GET`-only nature.
